### ISSUE TITLE
Can't start the container

### ISSUE THREAD

**Issue by Boss-man** [johannestang/yolo_service#1] opened 2020-01-04 07:35 UTC
All I'm getting in the log is 
`Try to load cfg: data/yolov3.cfg, weights: yolov3.weights, clear = 0 `
and then the container stops.

I'm trying to test it on my Synology DS918+ NAS.

**Comment by johannestang** [comment] 2020-01-04 13:40
It is not an issue I've encountered, but it could be caused by your NAS not having enough available memory. The container is quite memory hungry and if it runs out of memory it will die like you describe. I would suggest that you check the system log on the NAS and see if you can find any indications that the container is being killed because it is using too much memory.

**Comment by Boss-man** [comment] 2020-01-05 19:37
I have 4GB memory in my NAS, but the container stops right away, so it does not even get to consume any memory.

Maybe it just not works on a NAS. Just wanted to see how fast it could process the images, but I guess it would not be any good.

PS: Jeg er også dansk :)

**Comment by johannestang** [comment] 2020-01-07 15:04
The point where the container is stopping is where the trained model is loaded, so even though the container is stopping immediately it is consuming quite a bit of memory. That being said, it should be able to run in 4GB if you don't have too much other stuff running. I don't know how Synology manages its Docker environment, it could be that it limits how many resources the containers are allowed to use.

If you want to investigate it further you need to find the system log. If you can get into a terminal on the NAS you can just execute `dmesg`, otherwise you can probably find it somewhere in the GUI. If the container is being killed because it is using too much memory you should see something like this in the log:

```
Memory cgroup out of memory: Kill process 15369 (python3) score 1016 or sacrifice child
Killed process 15369 (python3) total-vm:2556220kB, anon-rss:518364kB, file-rss:11312kB, shmem-rss:0kB
oom_reaper: reaped process 15369 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

Let me know if you find something interesting, otherwise I'll close the issue.

Held og lykke :)

**Comment by Boss-man** [comment] 2020-01-08 18:14
I get this error:
`traps: python3[6209] trap invalid opcode ip:7fd8c0945d24 sp:7fff07fb8340 error:0 in libdarknet.so[7fd8c08c4000+e8000]`

I don't know what it means. But I guess it will not run on my CPU, maybe missing a specific instruction set.

**Comment by johannestang** [comment] 2020-01-08 19:37
That makes sense. You're right, it's a missing instruction set: AVX. If you remove this line:

https://github.com/johannestang/yolo_service/blob/14c1c207e36a520824a8dadf704a8e2d7721dc54/Dockerfile#L21

from the Dockerfile, then you can build a version of the image that doesn't require AVX.

**Comment by Boss-man** [comment] 2020-01-08 20:17
Cool.. Now it works.. 
Total BFLOPS: 65.864

Around 13 seconds for a scan of a car in 4912x2760 and doesn't seem to be faster with smaller images.

**Comment by johannestang** [comment] 2020-01-09 09:03
Great to hear :)

The image is resized before it's processed by the model, it has to be the same size as the images the model was trained on. Therefore the size of the image doesn't affect the speed. It can, however, have an effect on detection if the objects you're trying to detect become too small after resizing.

**Closed as completed by johannestang** 2020-01-09 09:03 UTC
